version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.build
    image: build
    container_name: build
    environment:
      DISPLAY: $DISPLAY
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
      - .:/usr/src/app

  linter:
    build:
      context: .
      dockerfile: ./docker/Dockerfile.linter
    image: linter
    container_name: linter
    volumes:
      - .:/usr/src/app
