name: Build project 

on:
  workflow_call:
  workflow_dispatch:

jobs:
  builder:
    name: Build project
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Build image
        run: |
          docker compose build app

      - name: Build project
        run: |
          docker compose run make build
