# Quiero que se carguen los jobs de linter.yml y de builder.yml

name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
      - uses: ./linter.yml

  builder:
    runs-on: ubuntu-latest
    steps:
      - uses: ./builder.yml
