# Quiero que se carguen los jobs de linter.yml y de builder.yml

name: Linter

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: .github/workflows/linter.yaml
      - uses: .github/workflows/builder.yaml
