# name: Linter

# on:
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

# jobs:
#   CI:
#     runs-on: ubuntu-latest
#     steps:
#       - name: Linter
#         uses: .github/workflows/linter.yaml
#       - name: Builder
#         uses: .github/workflows/builder.yaml
