name: Run linter and builder

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  linter:
    uses: ./.github/workflows/.reusable-workflow-linter.yaml

  builder:
    needs: linter
    uses: ./.github/workflows/.reusable-workflow-builder.yaml
